# Generated by Django 2.2 on 2020-08-13 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('hometown', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('work', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('home', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('cover', models.ImageField(blank=True, default='/coverdefault.jpg', null=True, upload_to='forums')),
                ('pic', models.ImageField(blank=True, default='/Default.png', null=True, upload_to='forums')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationships', models.ManyToManyField(related_name='friends', through='fblApp.Friend', to='fblApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=255)),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='forums')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('p_creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='fblApp.User')),
                ('p_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_by', to='fblApp.User')),
            ],
        ),
        migrations.AddField(
            model_name='friend',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='fblApp.User'),
        ),
        migrations.AddField(
            model_name='friend',
            name='flist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendlist', to='fblApp.User'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('c_creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fblApp.User')),
                ('c_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fblApp.Post')),
            ],
        ),
    ]
